name: Docker CI en CodeSpaces

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t codespace-lab:1.0 .

      - name: Mostrar imagen
        run: docker images